import {
  Users, Clock, CalendarDays, DollarSign, Briefcase,
  GraduationCap, FileText, BarChart3, Settings, CreditCard,
  Building2, UserPlus, ClipboardCheck, Target, Award,
  Megaphone, Receipt, CalendarCheck, Headphones, Package,
  CalendarClock, ScrollText, UsersRound,
  Network, UserX, Banknote, ClipboardList, Plane, DoorOpen, LogOut,
  Eye, Handshake, Shield, Timer, House, MessageCircle,
  BookOpen, Heart, Cake, Keyboard,
  FolderKanban, Sparkles, GitBranch, MessageSquare, Activity,
  Scale, Monitor, Map,
  Bot, Upload, Fingerprint, Umbrella, Landmark, LayoutTemplate,
  type LucideIcon
} from "lucide-react";

export interface NavItem {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: LucideIcon;
  href: string;
  color: string;
  category: "core" | "workforce" | "talent" | "admin";
}

export const MODULES: NavItem[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    shortName: "Home",
    description: "Overview & analytics",
    icon: BarChart3,
    href: "/dashboard",
    color: "oklch(0.65 0.18 250)",
    category: "core",
  },
  {
    id: "employees",
    name: "Employees",
    shortName: "People",
    description: "Employee directory & profiles",
    icon: Users,
    href: "/employees",
    color: "oklch(0.65 0.16 160)",
    category: "core",
  },
  {
    id: "departments",
    name: "Departments",
    shortName: "Depts",
    description: "Organization structure",
    icon: Building2,
    href: "/departments",
    color: "oklch(0.60 0.14 280)",
    category: "core",
  },
  {
    id: "attendance",
    name: "Attendance",
    shortName: "Clock",
    description: "Clock in/out & tracking",
    icon: Clock,
    href: "/attendance",
    color: "oklch(0.70 0.15 80)",
    category: "workforce",
  },
  {
    id: "leave",
    name: "Leave Management",
    shortName: "Leave",
    description: "Leave requests & approvals",
    icon: CalendarDays,
    href: "/leave",
    color: "oklch(0.65 0.17 30)",
    category: "workforce",
  },
  {
    id: "payroll",
    name: "Payroll",
    shortName: "Pay",
    description: "Salary, deductions & payslips",
    icon: DollarSign,
    href: "/payroll",
    color: "oklch(0.68 0.16 145)",
    category: "workforce",
  },
  {
    // Added so `benefits` is reachable from navigation: rbac.ts already defined a
    // "benefits.view" module permission, but no MODULES entry ever existed, so the
    // page (and its data) was only reachable by typing the URL directly.
    id: "benefits",
    name: "Benefits",
    shortName: "Benefits",
    description: "Health, insurance & benefit plans",
    icon: Umbrella,
    href: "/benefits",
    color: "oklch(0.66 0.17 165)",
    category: "workforce",
  },
  {
    // Same omission as `benefits` above, and with a worse consequence: an
    // employee cannot be paid until somebody has captured their account
    // details, and the page that captures them was reachable only by typing
    // the URL. A payroll run that fails for want of a bank account is traced
    // back to a form nobody could find.
    id: "bankdetails",
    name: "Bank Details",
    shortName: "Bank",
    description: "Your salary account & statutory IDs",
    icon: Landmark,
    href: "/bankdetails",
    color: "oklch(0.64 0.16 250)",
    category: "workforce",
  },
  {
    id: "recruitment",
    name: "Recruitment",
    shortName: "Hire",
    description: "Job postings & applicant tracking",
    icon: UserPlus,
    href: "/recruitment",
    color: "oklch(0.62 0.20 310)",
    category: "talent",
  },
  {
    id: "performance",
    name: "Performance",
    shortName: "Perf",
    description: "Reviews, goals & OKRs",
    icon: Target,
    href: "/performance",
    color: "oklch(0.60 0.22 15)",
    category: "talent",
  },
  {
    id: "training",
    name: "Training",
    shortName: "Learn",
    description: "Courses & certifications",
    icon: GraduationCap,
    href: "/training",
    color: "oklch(0.65 0.14 200)",
    category: "talent",
  },
  {
    id: "onboarding",
    name: "Onboarding",
    shortName: "Onboard",
    description: "New hire onboarding checklists",
    icon: ClipboardCheck,
    href: "/onboarding",
    color: "oklch(0.62 0.15 170)",
    category: "talent",
  },
  {
    // rbac.ts defines resignation.view/apply/approve/view_all in the same
    // change that adds this entry — a page with a permission and no MODULES
    // entry has shipped unreachable-by-nav twice already in this repo (see
    // the benefits and interns comments below), and this is the same pairing
    // discipline applied a fourth time.
    id: "resignation",
    name: "Resignation",
    shortName: "Resign",
    description: "Submit and track a resignation",
    icon: LogOut,
    href: "/resignation",
    color: "oklch(0.58 0.17 25)",
    category: "talent",
  },
  {
    // A third instance of the same gap as `benefits` and `bankdetails`
    // above: rbac.ts defines interns.view/interns.manage in the same change
    // that adds this entry, specifically so that pairing never breaks —
    // without a MODULES entry the page and its conversion action would only
    // be reachable by typing the URL directly, same as those two.
    id: "interns",
    name: "Interns",
    shortName: "Interns",
    description: "Internship end dates, conversion & documents",
    icon: GraduationCap,
    href: "/interns",
    color: "oklch(0.63 0.17 190)",
    category: "talent",
  },
  {
    id: "documents",
    name: "Documents",
    shortName: "Docs",
    description: "HR policies & employee docs",
    icon: FileText,
    href: "/documents",
    color: "oklch(0.58 0.12 240)",
    category: "admin",
  },
  // Added in the same change as the "templates.manage" permission in
  // rbac.ts, not after it. This codebase has shipped a permission with no
  // matching entry here at least twice (see benefits and bankdetails
  // above) — both times the page existed and worked, but only for someone
  // who typed the URL directly, because MODULE_PERMISSION_MAP gates the
  // route yet nothing in this list ever links to it.
  {
    id: "templates",
    name: "Document Templates",
    shortName: "Templates",
    description: "Edit letter & document templates",
    icon: LayoutTemplate,
    href: "/templates",
    color: "oklch(0.60 0.16 220)",
    category: "admin",
  },
  {
    id: "reports",
    name: "Reports",
    shortName: "Reports",
    description: "HR analytics & workforce insights",
    icon: BarChart3,
    href: "/reports",
    color: "oklch(0.55 0.18 260)",
    category: "admin",
  },
  {
    id: "awards",
    name: "Awards & Recognition",
    shortName: "Awards",
    description: "Employee recognition & rewards",
    icon: Award,
    href: "/awards",
    color: "oklch(0.72 0.18 60)",
    category: "talent",
  },
  {
    id: "settings",
    name: "Settings",
    shortName: "Settings",
    description: "Organization & app settings",
    icon: Settings,
    href: "/settings",
    color: "oklch(0.50 0.05 250)",
    category: "admin",
  },
  {
    id: "billing",
    name: "Subscription & Billing",
    shortName: "Billing",
    description: "Plans, billing & invoices",
    icon: CreditCard,
    href: "/billing",
    color: "oklch(0.55 0.20 320)",
    category: "admin",
  },
  {
    id: "jobs",
    name: "Careers",
    shortName: "Jobs",
    description: "Public job board for applicants",
    icon: Briefcase,
    href: "/careers",
    color: "oklch(0.60 0.15 120)",
    category: "talent",
  },
  {
    id: "announcements",
    name: "Announcements",
    shortName: "News",
    description: "Company-wide announcements",
    icon: Megaphone,
    href: "/announcements",
    color: "oklch(0.62 0.18 340)",
    category: "core",
  },
  {
    id: "expenses",
    name: "Expenses",
    shortName: "Expense",
    description: "Expense claims & reimbursements",
    icon: Receipt,
    href: "/expenses",
    color: "oklch(0.60 0.16 35)",
    category: "workforce",
  },
  {
    id: "holidays",
    name: "Holiday Calendar",
    shortName: "Holidays",
    description: "Company holidays & events",
    icon: CalendarCheck,
    href: "/holidays",
    color: "oklch(0.65 0.15 150)",
    category: "workforce",
  },
  {
    id: "helpdesk",
    name: "Helpdesk",
    shortName: "Help",
    description: "Employee tickets & grievances",
    icon: Headphones,
    href: "/helpdesk",
    color: "oklch(0.58 0.16 220)",
    category: "admin",
  },
  {
    id: "assets",
    name: "Assets",
    shortName: "Assets",
    description: "Company asset tracking",
    icon: Package,
    href: "/assets",
    color: "oklch(0.55 0.14 180)",
    category: "admin",
  },
  {
    id: "shifts",
    name: "Shift Management",
    shortName: "Shifts",
    description: "Work shift scheduling",
    icon: CalendarClock,
    href: "/shifts",
    color: "oklch(0.62 0.14 100)",
    category: "workforce",
  },
  {
    id: "audit",
    name: "Audit Log",
    shortName: "Audit",
    description: "System activity & audit trail",
    icon: ScrollText,
    href: "/audit",
    color: "oklch(0.50 0.10 250)",
    category: "admin",
  },
  {
    id: "teams",
    name: "Teams",
    shortName: "Teams",
    description: "Team directory & collaboration",
    icon: UsersRound,
    href: "/teams",
    color: "oklch(0.58 0.18 270)",
    category: "core",
  },
  {
    id: "orgchart",
    name: "Org Chart",
    shortName: "Org",
    description: "Visual organization hierarchy",
    icon: Network,
    href: "/orgchart",
    color: "oklch(0.55 0.16 230)",
    category: "core",
  },
  {
    id: "offboarding",
    name: "Offboarding",
    shortName: "Exit",
    description: "Exit management & clearance",
    icon: UserX,
    href: "/offboarding",
    color: "oklch(0.55 0.18 10)",
    category: "talent",
  },
  {
    id: "loans",
    name: "Loans & Advances",
    shortName: "Loans",
    description: "Employee loans & salary advances",
    icon: Banknote,
    href: "/loans",
    color: "oklch(0.60 0.14 130)",
    category: "workforce",
  },
  {
    id: "surveys",
    name: "Surveys",
    shortName: "Survey",
    description: "Employee engagement surveys",
    icon: ClipboardList,
    href: "/surveys",
    color: "oklch(0.58 0.16 300)",
    category: "talent",
  },
  {
    id: "travel",
    name: "Travel Requests",
    shortName: "Travel",
    description: "Business travel management",
    icon: Plane,
    href: "/travel",
    color: "oklch(0.62 0.16 210)",
    category: "workforce",
  },
  {
    id: "meetings",
    name: "Meeting Rooms",
    shortName: "Rooms",
    description: "Room booking & scheduling",
    icon: DoorOpen,
    href: "/meetings",
    color: "oklch(0.55 0.14 190)",
    category: "admin",
  },
  {
    id: "visitors",
    name: "Visitors",
    shortName: "Visit",
    description: "Visitor passes & management",
    icon: Eye,
    href: "/visitors",
    color: "oklch(0.58 0.15 260)",
    category: "admin",
  },
  {
    id: "referrals",
    name: "Referrals",
    shortName: "Refer",
    description: "Employee referral tracking",
    icon: Handshake,
    href: "/referrals",
    color: "oklch(0.62 0.17 170)",
    category: "talent",
  },
  {
    id: "policies",
    name: "Policies",
    shortName: "Policy",
    description: "Company policies & handbook",
    icon: Shield,
    href: "/policies",
    color: "oklch(0.50 0.12 240)",
    category: "admin",
  },
  {
    id: "overtime",
    name: "Overtime",
    shortName: "OT",
    description: "Overtime tracking & approvals",
    icon: Timer,
    href: "/overtime",
    color: "oklch(0.60 0.18 50)",
    category: "workforce",
  },
  {
    id: "wfh",
    name: "Work From Home",
    shortName: "WFH",
    description: "Remote work requests",
    icon: House,
    href: "/wfh",
    color: "oklch(0.58 0.16 140)",
    category: "workforce",
  },
  {
    id: "feedback",
    name: "Feedback",
    shortName: "Feedback",
    description: "Suggestions & feedback box",
    icon: MessageCircle,
    href: "/feedback",
    color: "oklch(0.60 0.15 290)",
    category: "core",
  },
  {
    id: "knowledgebase",
    name: "Knowledge Base",
    shortName: "KB",
    description: "FAQs & how-to guides",
    icon: BookOpen,
    href: "/knowledgebase",
    color: "oklch(0.55 0.13 200)",
    category: "admin",
  },
  {
    id: "wellness",
    name: "Wellness",
    shortName: "Wellness",
    description: "Employee wellness program",
    icon: Heart,
    href: "/wellness",
    color: "oklch(0.62 0.20 350)",
    category: "talent",
  },
  {
    id: "celebrations",
    name: "Celebrations",
    shortName: "Celebrate",
    description: "Birthdays & work anniversaries",
    icon: Cake,
    href: "/celebrations",
    color: "oklch(0.68 0.18 50)",
    category: "core",
  },
  {
    id: "resourceplanner",
    name: "Resource Planner",
    shortName: "Resources",
    description: "Project resource allocation & capacity",
    icon: FolderKanban,
    href: "/resourceplanner",
    color: "oklch(0.58 0.18 280)",
    category: "admin",
  },
  {
    id: "culturehub",
    name: "Culture Hub",
    shortName: "Culture",
    description: "Values, recognition & traditions",
    icon: Sparkles,
    href: "/culturehub",
    color: "oklch(0.65 0.20 340)",
    category: "core",
  },
  {
    id: "workflows",
    name: "Workflows",
    shortName: "Flows",
    description: "HR workflow automation & approval chains",
    icon: GitBranch,
    href: "/workflows",
    color: "oklch(0.55 0.16 260)",
    category: "admin",
  },
  {
    id: "wall",
    name: "Engagement Wall",
    shortName: "Wall",
    description: "Social feed, kudos & celebrations",
    icon: MessageSquare,
    href: "/wall",
    color: "oklch(0.62 0.18 30)",
    category: "core",
  },
  {
    id: "orghealth",
    name: "Org Health",
    shortName: "Health",
    description: "Organization vitals & risk insights",
    icon: Activity,
    href: "/orghealth",
    color: "oklch(0.60 0.20 150)",
    category: "admin",
  },
  {
    id: "compensation",
    name: "Compensation",
    shortName: "Comp",
    description: "Benchmarking & pay equity analysis",
    icon: Scale,
    href: "/compensation",
    color: "oklch(0.58 0.16 100)",
    category: "workforce",
  },
  {
    id: "provisioning",
    name: "IT Provisioning",
    shortName: "IT",
    description: "Hardware, software & access management",
    icon: Monitor,
    href: "/provisioning",
    color: "oklch(0.55 0.14 210)",
    category: "admin",
  },
  {
    id: "journey",
    name: "Employee Journey",
    shortName: "Journey",
    description: "Full employee lifecycle map",
    icon: Map,
    href: "/journey",
    color: "oklch(0.60 0.17 300)",
    category: "talent",
  },
  {
    id: "chatbot",
    name: "HR Assistant",
    shortName: "AI Bot",
    description: "AI-powered HR chatbot",
    icon: Bot,
    href: "/chatbot",
    color: "oklch(0.62 0.20 280)",
    category: "core",
  },
  {
    id: "selfservice",
    name: "Self Service",
    shortName: "Self",
    description: "Employee self-service kiosk",
    icon: Fingerprint,
    href: "/selfservice",
    color: "oklch(0.58 0.18 160)",
    category: "core",
  },
  {
    id: "dataimport",
    name: "Data Center",
    shortName: "Data",
    description: "Import & export HR data",
    icon: Upload,
    href: "/dataimport",
    color: "oklch(0.55 0.14 220)",
    category: "admin",
  },
  {
    id: "admin",
    name: "Admin Console",
    shortName: "Admin",
    description: "System administration & monitoring",
    icon: Shield,
    href: "/admin",
    color: "oklch(0.50 0.16 260)",
    category: "admin",
  },
  {
    id: "analytics",
    name: "Analytics",
    shortName: "Analytics",
    description: "Advanced HR analytics & charts",
    icon: BarChart3,
    href: "/analytics",
    color: "oklch(0.58 0.20 280)",
    category: "admin",
  },
];

export const MODULE_CATEGORIES: Record<string, string> = {
  core: "Core",
  workforce: "Workforce",
  talent: "Talent",
  admin: "Administration",
};

export function groupModulesByCategory() {
  return Object.entries(MODULE_CATEGORIES).map(([key, label]) => ({
    key,
    label,
    items: MODULES.filter((m) => m.category === key),
  }));
}

export const SUBSCRIPTION_PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: 3,
    currency: "USD",
    interval: "per employee/month",
    maxEmployees: 25,
    features: [
      "Employee Directory",
      "Attendance Tracking",
      "Leave Management",
      "Basic Reports",
      "5 GB Storage",
      "Email Support",
    ],
    color: "from-blue-500 to-cyan-500",
    popular: false,
  },
  {
    id: "professional",
    name: "Professional",
    price: 8,
    currency: "USD",
    interval: "per employee/month",
    maxEmployees: 200,
    features: [
      "Everything in Starter",
      "Payroll Management",
      "Recruitment & ATS",
      "Performance Reviews",
      "Training & LMS",
      "Onboarding Workflows",
      "Awards & Recognition",
      "Advanced Analytics",
      "50 GB Storage",
      "Priority Support",
    ],
    color: "from-violet-500 to-purple-600",
    popular: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 15,
    currency: "USD",
    interval: "per employee/month",
    maxEmployees: -1,
    features: [
      "Everything in Professional",
      "Unlimited Employees",
      "Custom Branding",
      "API Access",
      "SSO / SAML",
      "Audit Logs",
      "Dedicated Account Manager",
      "Custom Integrations",
      "Unlimited Storage",
      "24/7 Phone Support",
      "SLA Guarantee",
    ],
    color: "from-amber-500 to-orange-600",
    popular: false,
  },
] as const;
