// @vitest-environment node
//
// pdf-lib compresses page content streams, so a saved PDF's bytes do not
// contain the literal text we drew — there is no cheap "does the output
// contain the word Hello" assertion to reach for here. Two levels of test
// follow from that: `htmlToBlocks` is a pure function with fully inspectable
// output, so the actual reading-comprehension behaviour (block boundaries,
// heading/subheading classification, table rows collapsing to "Label:
// Value", entity decoding) is tested there directly and thoroughly.
// `renderDocumentPdf` itself is then tested as a black box against the one
// property that matters and is externally observable without a text layer:
// it always returns a real, loadable PDF, and it never truncates — content
// that does not fit on one page produces more pages, it does not disappear.

import { describe, expect, it, vi } from "vitest";
import { PDFDocument } from "pdf-lib";
import { deflateSync } from "node:zlib";
import { htmlToBlocks, renderDocumentPdf, type DocumentPdfSignatory } from "./render-pdf";

// ─── A minimal, self-generated PNG fixture ──────────────────
//
// jsdom has no canvas 2D context and this module has no business shipping a
// checked-in binary fixture for two grey pixels, so the test builds the
// smallest legal PNG itself: signature + IHDR + one uncompressed-filter
// scanline pair + IEND, each chunk CRC32'd per the PNG spec. It exists only
// to give `PDFDocument.embedPng` something structurally real to accept.
function crc32(bytes: Uint8Array): number {
  let crc = ~0;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return ~crc >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const typeBytes = Buffer.from(type, "ascii");
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const crcInput = Buffer.concat([typeBytes, data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(crcInput), 0);
  return Buffer.concat([length, crcInput, crc]);
}

function tinySignaturePngDataUrl(): string {
  const width = 2;
  const height = 2;
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour (RGB)
  // bytes 10-12 (compression, filter, interlace) default to 0, already zeroed by Buffer.alloc

  const rowBytes = 1 + width * 3; // leading filter-type byte + 3 bytes/pixel
  const raw = Buffer.alloc(rowBytes * height, 0x80);
  for (let row = 0; row < height; row += 1) raw[row * rowBytes] = 0; // filter type "None"

  const png = Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", deflateSync(raw)),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
  return `data:image/png;base64,${png.toString("base64")}`;
}

// ─── htmlToBlocks ────────────────────────────────────────────

// Shaped like the real `seed-letter-templates.mjs` output: a full document
// (doctype/head/style/script), comments, the `wrapper`/`wrapper-inner` div
// nesting every template uses, a true heading, `<p class="section-title">`
// section headings, a `<br/>` inside a paragraph, a data table, and a list —
// every block-level shape this reader has to understand at once.
const SAMPLE_TEMPLATE_HTML = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><title>Offer Letter</title><style>body{font-family:sans-serif}</style><script>console.log("noop")</script></head>
<body>
<!-- generated by seed-letter-templates -->
<div class="wrapper"><div class="wrapper-inner">
<h1>Offer of Employment</h1>
<p>Dear Asha Verma,</p>
<p>We are pleased to confirm your appointment.<br/>Please review the terms below.</p>
<p class="section-title">Compensation</p>
<table class="data"><tbody>
<tr><th>Annual CTC</th><td>Rs. 12,00,000</td></tr>
<tr><th>Effective Date</th><td>1 April 2024</td></tr>
</tbody></table>
<p class="section-title">Next steps</p>
<ul><li>Sign and return this letter</li><li>Bring original documents on day one</li></ul>
<p>Regards &amp; best wishes,<br/>People Team</p>
</div></div>
</body></html>`;

describe("htmlToBlocks", () => {
  it("drops the doctype, head, style, script and comments entirely", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    const joined = blocks.map((block) => block.text).join(" | ");
    expect(joined).not.toMatch(/font-family|console\.log|generated by seed-letter-templates|DOCTYPE/);
  });

  it("classifies a true heading as 'heading' and an ordinary paragraph as 'text'", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    expect(blocks[0]).toEqual({ text: "Offer of Employment", kind: "heading" });
    expect(blocks.find((block) => block.text.startsWith("Dear Asha"))?.kind).toBe("text");
  });

  it('classifies <p class="section-title"> as a subheading, not body text', () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    expect(blocks.find((block) => block.text === "Compensation")?.kind).toBe("subheading");
    expect(blocks.find((block) => block.text === "Next steps")?.kind).toBe("subheading");
  });

  it("never emits a spurious empty block for a wrapper div that carries no text of its own", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    expect(blocks.some((block) => block.text.trim().length === 0)).toBe(false);
    // The two nesting wrapper divs and the table/tbody scaffolding must not
    // have produced anything at all, empty or otherwise.
    expect(blocks.some((block) => block.text === "wrapper")).toBe(false);
  });

  it("keeps a <br/> as a real line break inside one block rather than merging or splitting the paragraph", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    const paragraph = blocks.find((block) => block.text.startsWith("We are pleased"));
    expect(paragraph?.text).toBe("We are pleased to confirm your appointment.\nPlease review the terms below.");
  });

  it("joins a <tr><th>/<td> data row into a single 'Label: Value' line", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    expect(blocks.find((block) => block.text.startsWith("Annual CTC"))?.text).toBe("Annual CTC: Rs. 12,00,000");
    expect(blocks.find((block) => block.text.startsWith("Effective Date"))?.text).toBe("Effective Date: 1 April 2024");
    // Two rows in the same table must stay two lines, not run together.
    expect(blocks.filter((block) => block.kind === "text" && block.text.includes(": ")).length).toBe(2);
  });

  it("prefixes list items with a bullet and keeps each <li> as its own block", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    expect(blocks.find((block) => block.text.includes("Sign and return"))?.text).toBe("\u2022 Sign and return this letter");
    expect(blocks.find((block) => block.text.includes("Bring original"))?.text).toBe("\u2022 Bring original documents on day one");
  });

  it("decodes the named entity used by the real templates (&amp;) inline", () => {
    const blocks = htmlToBlocks(SAMPLE_TEMPLATE_HTML);
    expect(blocks.find((block) => block.text.includes("best wishes"))?.text).toBe("Regards & best wishes,\nPeople Team");
  });

  it("decodes decimal and hexadecimal numeric character references", () => {
    const blocks = htmlToBlocks("<p>&#65;&#x42;&#67;</p>");
    expect(blocks[0]?.text).toBe("ABC");
  });

  it("leaves an entity it does not recognise exactly as written rather than deleting it", () => {
    const blocks = htmlToBlocks("<p>Balance: &notarealentity;</p>");
    expect(blocks[0]?.text).toBe("Balance: &notarealentity;");
  });

  it("returns an empty list for a document with no readable text at all", () => {
    expect(htmlToBlocks("<html><head><style>body{color:red}</style></head><body></body></html>")).toEqual([]);
  });
});

// ─── renderDocumentPdf ───────────────────────────────────────

describe("renderDocumentPdf", () => {
  const baseParams = {
    title: "Offer of Employment",
    companyName: "Circuvent Technologies Pvt Ltd",
    signingReference: "b5a35e3e-2f2b-4b8a-9c2e-4a1a6a9b7a10",
  };

  it("produces bytes that are a real, loadable PDF for a short document", async () => {
    const bytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: "<p>Hello there.</p>", signatories: [] });
    expect(Buffer.from(bytes.slice(0, 5)).toString("ascii")).toBe("%PDF-");
    const loaded = await PDFDocument.load(bytes);
    expect(loaded.getPageCount()).toBeGreaterThanOrEqual(1);
  });

  it("renders a rupee sign instead of failing to encode it", async () => {
    // The standard-14 fonts this used are WinAnsi and have no ₹, so pdf-lib
    // threw `WinAnsi cannot encode "₹" (0x20b9)` on every document carrying a
    // salary — every offer letter and every compensation revision. The
    // failure surfaced only in the PDF storage outbox as a retry that could
    // never succeed, so the documents existed with no archived PDF and nobody
    // could download one.
    const bytes = await renderDocumentPdf({
      ...baseParams,
      bodyHtmlOrText: "<p>Revised annual cost to company: ₹13,20,000</p>",
      signatories: [],
    });
    expect(Buffer.from(bytes.slice(0, 5)).toString("ascii")).toBe("%PDF-");
    expect((await PDFDocument.load(bytes)).getPageCount()).toBeGreaterThanOrEqual(1);
  });

  it("renders the other characters an Indian HR document actually contains", async () => {
    // An em dash and curly quotes come from the letter templates themselves;
    // the Devanagari is here because a legal name can carry it and a name
    // that cannot be printed is a document that cannot be issued.
    const bytes = await renderDocumentPdf({
      ...baseParams,
      bodyHtmlOrText: "<p>“Employee” — ₹1,00,000 — हेमा · ✓</p>",
      signatories: [],
    });
    expect((await PDFDocument.load(bytes)).getPageCount()).toBeGreaterThanOrEqual(1);
  });

  it("still yields one real page for an empty body and no signatories, never zero pages", async () => {
    const bytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: "", signatories: [] });
    const loaded = await PDFDocument.load(bytes);
    expect(loaded.getPageCount()).toBe(1);
  });

  it("flows long content onto additional pages instead of truncating it", async () => {
    const paragraph = `<p>${"This clause repeats to occupy real vertical space on the printed page. ".repeat(6)}</p>`;

    const shortBytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: paragraph.repeat(2), signatories: [] });
    const longBytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: paragraph.repeat(80), signatories: [] });

    const shortPages = (await PDFDocument.load(shortBytes)).getPageCount();
    const longPages = (await PDFDocument.load(longBytes)).getPageCount();

    expect(shortPages).toBe(1);
    // 80 repeats of a six-sentence paragraph is tens of thousands of
    // characters of wrapped body text — nowhere close to fitting in the two
    // or three pages a truncation bug would still manage to produce.
    expect(longPages).toBeGreaterThan(shortPages);
    expect(longPages).toBeGreaterThanOrEqual(5);
  });

  it("omits the signature section entirely when no one has signed", async () => {
    const bytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: "<p>Short body.</p>", signatories: [] });
    const loaded = await PDFDocument.load(bytes);
    expect(loaded.getPageCount()).toBe(1);
  });

  it("lays out every signatory in the array, not only the first", async () => {
    const shortBody = "<p>Short body.</p>";
    const noSignatories = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: shortBody, signatories: [] });

    // A template can require more than one signature (`["employee", "hr"]`
    // is the common case in this catalog's own seed data). Twenty embedded
    // signature images cannot possibly fit in what one page has left after
    // a one-line body — if a bug ever dropped everything past
    // `signatories[0]`, this document would still be exactly one page.
    const manySignatories: DocumentPdfSignatory[] = Array.from({ length: 20 }, (_, index) => ({
      name: `Signatory Number ${index + 1}`,
      role: index % 2 === 0 ? "employee" : "hr",
      signedAt: new Date("2024-04-01T10:00:00.000Z"),
      signatureImageDataUrl: tinySignaturePngDataUrl(),
    }));
    const withManySignatories = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: shortBody, signatories: manySignatories });

    const noSigPages = (await PDFDocument.load(noSignatories)).getPageCount();
    const manySigPages = (await PDFDocument.load(withManySignatories)).getPageCount();

    expect(noSigPages).toBe(1);
    expect(manySigPages).toBeGreaterThan(noSigPages);
  });

  it("embeds a genuine signature image without error", async () => {
    const signatories: DocumentPdfSignatory[] = [
      {
        name: "Priya Nair",
        role: "employee",
        signedAt: new Date("2024-04-03T12:00:00.000Z"),
        signatureImageDataUrl: tinySignaturePngDataUrl(),
      },
    ];
    const bytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: "<p>Short body.</p>", signatories });
    const loaded = await PDFDocument.load(bytes);
    expect(loaded.getPageCount()).toBeGreaterThanOrEqual(1);
  });

  it("falls back to a text-only signature line when the image cannot be embedded, without failing the render", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    const signatories: DocumentPdfSignatory[] = [
      {
        name: "Rahul Singh",
        role: "hr",
        signedAt: new Date("2024-04-02T09:15:00.000Z"),
        // Not a real PNG — this is precisely the "a signature that fails to
        // upload [or otherwise misbehaves]" class of input the feature must
        // survive without losing the fact that someone did sign.
        signatureImageDataUrl: "data:image/png;base64,dGhpcyBpcyBub3QgYSBwbmc=",
      },
    ];

    const bytes = await renderDocumentPdf({ ...baseParams, bodyHtmlOrText: "<p>Short body.</p>", signatories });

    expect(Buffer.from(bytes.slice(0, 5)).toString("ascii")).toBe("%PDF-");
    expect(warn).toHaveBeenCalled();
    warn.mockRestore();
  });

  it("does not throw for a pathologically long company name or title", async () => {
    await expect(
      renderDocumentPdf({
        title: "T".repeat(400),
        companyName: "C".repeat(400),
        signingReference: baseParams.signingReference,
        bodyHtmlOrText: "<p>Short body.</p>",
        signatories: [],
      })
    ).resolves.toBeInstanceOf(Uint8Array);
  });
});
